name: Validate PR Title & Body

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR format
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title;
            const body = pr.body || '';

            // Must match exactly one LIA-XXXX
            const ticketMatches = title.match(/LIA-\d+/g) || [];
            const isTitleValid = ticketMatches.length === 1;
            const hasScreenshot = /!\[.*\]\([^)]+\.(png|jpg|jpeg|gif)(\?[^)]*)?\)/i.test(body);
            const hasVideo = /(loom\.com|\.mp4|\.webm)/i.test(body);
            const isVisualProofAttached = hasScreenshot || hasVideo;

            let messages = [];

            if (!isTitleValid) {
              if (ticketMatches.length === 0) {
                messages.push("❌ **PR title must include one ticket in the format 'LIA-XXXX'** (e.g., `LIA-1234`).");
              } else {
                messages.push("❌ **PR title must contain only *one* ticket in the format 'LIA-XXXX'**. Multiple ticket IDs are not allowed.");
              }
            }

            if (!isVisualProofAttached) {
              messages.push("❌ **PR must include either a screenshot or video** as proof.");
            }

            if (messages.length > 0) {
              const comment = [
                `Hi @${pr.user.login},`,
                '',
                "Your pull request has been **automatically closed** because it didn't meet the required format:",
                '',
                ...messages.map(m => `- ${m}`),
                '',
                'Please update your PR and open a new one when it\'s ready.'
              ].join('\n');

              await github.rest.issues.createComment({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });

              await github.rest.pulls.update({
                pull_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "closed"
              });

              core.setFailed("PR closed due to format violations.");
            }
